# Generated by Django 3.0.6 on 2020-06-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200623_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientCategory')),
            ],
        ),
        migrations.AlterField(
            model_name='clientcategoryversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CategoryVersion'),
        ),
    ]
