# Generated by Django 3.0.6 on 2020-06-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200623_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcategoryversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CategoryVersion'),
        ),
    ]
