# Generated by Django 3.0.5 on 2020-05-13 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='div_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
