# Generated by Django 3.0.5 on 2020-05-13 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cliente_div_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='div_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
