# Generated by Django 3.0.6 on 2020-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_clientcategoryrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategoryrelation',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientcategoryrelation',
            name='urlcentral',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
