# Generated by Django 3.0.6 on 2020-05-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200525_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientcategoryrelation',
            unique_together={('categorie', 'client')},
        ),
    ]
