# Generated by Django 3.0.6 on 2020-06-24 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20200530_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCategoryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('clientCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientCategoryRelation')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CategoryVersion')),
            ],
        ),
    ]
