# Generated by Django 3.0.6 on 2020-08-04 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_categoryversion_clientcategoryversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solic_date', models.DateTimeField(auto_now_add=True)),
                ('atend_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('F', 'Finalizado')], max_length=1)),
                ('atend_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente', to=settings.AUTH_USER_MODEL)),
                ('solic_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('solic_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientCategoryVersion')),
            ],
        ),
    ]
