# Generated by Django 3.0.6 on 2020-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_clientbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbackup',
            name='atend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
