# Generated by Django 3.0.6 on 2020-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200803_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbackup',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
