# Generated by Django 3.0.6 on 2020-08-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_clientbackup_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbackup',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientCategoryRelation'),
            preserve_default=False,
        ),
    ]
