# Generated by Django 3.0.6 on 2020-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_clientbackup_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('user', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
