# Generated by Django 3.0.6 on 2020-08-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_backupdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbackup',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.BackupDestination'),
        ),
    ]
