# Generated by Django 3.0.6 on 2020-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_clientbackup_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdestination',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
