# Generated by Django 3.0.6 on 2020-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_backupdestination_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdestination',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
